name: AlertPlugin
version: 1.0.0
main: io.papermc.alertplugin.Main
description: Simple alert plugin
author: pairnon
website: https://github.com/pairnon/AlertPlugin
api-version: '1.20'
commands:
  restartalert:
    description: Begin timed restart alerts
    usage: restartalert