name: AlertPlugin
version: 1.0.2
main: io.papermc.alertplugin.Main
description: Alert scheduler
author: pairnon
website: https://github.com/pairnon/AlertPlugin
api-version: '1.20'
commands:
  beginrestartalerts:
    description: Begin timed restart alerts
    usage: beginrestartalerts
    aliases: [bra]
  cancelrestartalerts:
    description: Cancel timed restart alerts
    usage: cancelrestartalerts
    aliases: [cra]